name: Build And Deploy
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build image
        run: make build-image

      - name: push the image
        run: make build-image-push
        env:
          AWS_DEFAULT_REGION: ${{vars.AWS_DEFAULT_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  test:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: pull the image
        run: make build-image-pull
        env:
          AWS_DEFAULT_REGION: ${{vars.AWS_DEFAULT_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: make the database up
        run: make up

      - name: make build image migrate
        run: make build-image-migrate
        env:
          GOOSE_DBSTRING: postgresql://postgres:password@localhost:5432/postgres?sslmode=disable
          GOOSE_DRIVER: postgres

      - if: always()
        run: make down
